# frozen_string_literal: true

source 'https://rubygems.org'
gem 'activerecord', '~> 5.2.2'
gem 'debase'
gem 'minitest', '~> 5.11.3'
gem 'rake', '~> 12.3.2'
gem 'rubocop', '~> 0.63.1'
gem 'ruby-debug-ide'
gem 'sqlite3', '~> 1.3.6', git: "https://github.com/larskanis/sqlite3-ruby", branch: "add-gemspec"
gem 'rdoc'
