require 'rake/testtask'

desc 'Run all tasks'
task :all do
  Rake::Task[:rubocop].invoke
  Rake::Task[:test].invoke
end

desc 'Run rubocop'
task :rubocop do
  require 'rubocop/rake_task'
  RuboCop::RakeTask.new
end

desc 'Run tests'
Rake::TestTask.new(:test) do |t|
  t.libs << 'test'
  t.libs << 'lib'
  t.libs << 'lib/courses'
  t.libs << 'lib/students'
  t.test_files = FileList['test/**/test_*.rb']
end

task default: :all
